baseURL = "https://marasoon.com"
languageCode = "zh-CN"
title = "é©¬æ‹‰æ¾ç ´ä¸‰è·‘è€…çš„åˆ†äº«"
theme="archie"
copyright = "Â© Minus Tech"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
googleAnalytics = "G-BLPGFLQ3N6"

[params]
	mode="auto"
	useCDN=false
	subtitle = "ğŸƒæ¯ä¸ªè·‘è€…çš„ç ´ä¸‰ä¹‹è·¯éƒ½ä¸ä¸€æ ·ï¼Œæ‰¾åˆ°å®ƒï¼Œè·‘ä¸‹å»ğŸ‰"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://github.com/hagerhu"

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/hagerhu"

[[menu.main]]
name = "Home"
url = "/"
weight = 1
